# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Jilin1Tiles
                                 A QGIS plugin
 Jilin1Tiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-19
        copyright            : (C) 2023 by yoyi
        email                : pengzhijue@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Jilin1Tiles class from file Jilin1Tiles.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Jilin1Tiles import Jilin1Tiles
    return Jilin1Tiles(iface)
