# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Jilin1Tiles_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jilin1TilesDialogBase(object):
    def setupUi(self, Jilin1TilesDialogBase):
        Jilin1TilesDialogBase.setObjectName("Jilin1TilesDialogBase")
        Jilin1TilesDialogBase.resize(424, 411)
        self.verticalLayout = QtWidgets.QVBoxLayout(Jilin1TilesDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Jilin1TilesDialogBase)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Jilin1TilesDialogBase)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.intoWeb = QtWidgets.QPushButton(Jilin1TilesDialogBase)
        self.intoWeb.setObjectName("intoWeb")
        self.horizontalLayout_3.addWidget(self.intoWeb)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Jilin1TilesDialogBase)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tkLE = QtWidgets.QLineEdit(Jilin1TilesDialogBase)
        self.tkLE.setObjectName("tkLE")
        self.horizontalLayout_2.addWidget(self.tkLE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(Jilin1TilesDialogBase)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.listView = QtWidgets.QListView(Jilin1TilesDialogBase)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)

        self.retranslateUi(Jilin1TilesDialogBase)
        QtCore.QMetaObject.connectSlotsByName(Jilin1TilesDialogBase)

    def retranslateUi(self, Jilin1TilesDialogBase):
        _translate = QtCore.QCoreApplication.translate
        Jilin1TilesDialogBase.setWindowTitle(_translate("Jilin1TilesDialogBase", "Jilin1Tiles"))
        self.label.setText(_translate("Jilin1TilesDialogBase", "吉林一号切片影像查看器 Beta版"))
        self.label_3.setText(_translate("Jilin1TilesDialogBase", "点击按钮访问吉林一号切片影像套件网站获得体验版TK"))
        self.intoWeb.setText(_translate("Jilin1TilesDialogBase", "点我进入"))
        self.label_2.setText(_translate("Jilin1TilesDialogBase", "请输入您的TK"))
        self.label_4.setText(_translate("Jilin1TilesDialogBase", "双击加载图层"))
